language: scala

jdk: oraclejdk8

scala:
- 2.12.8

script:
- sbt ++$TRAVIS_SCALA_VERSION dist
- sbt ++$TRAVIS_SCALA_VERSION docker:publishLocal
- HEROKU_API_KEY="a9f12619-1568-4756-aa69-fbd1cf15688d" sbt ++$TRAVIS_SCALA_VERSION stage deployHeroku